#  Camera Calibration (Theory Section with Answers)

---

## Q1. Image Formation Process (10 marks)

**Q:** Explain the two parts of the image formation process in computer vision.  

**A:**  
1. **Geometry of Image Formation** – Determines where a 3D point projects onto the 2D image plane (pinhole/lens model).  
2. **Photometric Image Formation** – Determines pixel brightness based on illumination, reflectance, and sensor response.  

---

## Q2. Pinhole Camera Model (15 marks)

**Q:** Derive the perspective projection equation using the pinhole camera model.  

**A:**  
Using similar triangles:  

For a 3D point $(X,Y,Z)$ projected to an image point $(x,y)$ with focal length $f$:  

\[
\frac{x}{f} = \frac{X}{Z}, 
\quad 
\frac{y}{f} = \frac{Y}{Z}
\]

Therefore:  

\[
x = \frac{fX}{Z}, 
\quad 
y = \frac{fY}{Z}
\]


This is the **perspective projection equation**, nonlinear in Cartesian coordinates.  

---

# Q2. Pinhole Camera Model (15 marks)

**Q:** Derive the perspective projection equation using the pinhole camera model.

---

**A:**  
Using similar triangles:

For a 3D point $(X, Y, Z)$ projected to an image point $(x, y)$ with focal length $f$:

$$
\frac{x}{f} = \frac{X}{Z}, \quad \frac{y}{f} = \frac{Y}{Z}
$$

Therefore:

$$
x = \frac{fX}{Z}, \quad y = \frac{fY}{Z}
$$

This is the **perspective projection equation**, nonlinear in Cartesian coordinates.


## Q3. Homogeneous Coordinates (10 marks)

**Q:** Explain why homogeneous coordinates are used in perspective projection.  

---

**A:**  
- Homogeneous coordinates allow perspective projection to be represented as a **linear matrix multiplication**.  

A 3D point $(X, Y, Z, 1)$ is projected as:

$$
\begin{bmatrix}
x' \\ y' \\ w
\end{bmatrix}
=
\begin{bmatrix}
f & 0 & 0 & 0 \\
0 & f & 0 & 0 \\
0 & 0 & 1 & 0
\end{bmatrix}
\begin{bmatrix}
X \\ Y \\ Z \\ 1
\end{bmatrix}
$$

Normalized image coordinates:

$$
x = \frac{x'}{w}, 
\quad 
y = \frac{y'}{w}
$$

This compact form **simplifies projection equations** and makes them easy to handle in matrix form.  

---

## Q4. Intrinsic vs Extrinsic Parameters (15 marks)

**Q:** Define intrinsic and extrinsic camera parameters with their matrix forms.  

---

**A:**  

### 🔹 Intrinsic Parameters ($K$)  
These describe the **internal geometry** of the camera:

$$
K =
\begin{bmatrix}
f_x & s & c_x \\
0   & f_y & c_y \\
0   & 0   & 1
\end{bmatrix}
$$

- $f_x, f_y$: focal lengths (in pixels)  
- $c_x, c_y$: principal point (image center offset)  
- $s$: skew (accounts for non-rectangular pixels, usually $0$)  

---

### 🔹 Extrinsic Parameters ($[R|t]$)  
These describe the **pose of the camera** in the world coordinate system:  

- $R$: rotation matrix (3×3)  
- $t$: translation vector (3×1)  

---

### 📐 Projection Equation  

$$
\begin{bmatrix}
u \\ v \\ 1
\end{bmatrix}
\;\sim\;
K [R|t]
\begin{bmatrix}
X \\ Y \\ Z \\ 1
\end{bmatrix}
$$

Where:  
- $(X, Y, Z, 1)^T$ are 3D world coordinates  
- $(u, v, 1)^T$ are corresponding 2D image points  

---

---

---

## Q5. Distortion Parameters (10 marks)

**Q:** Explain radial and tangential distortions in cameras.  

---

**A:**  

### 🔹 Radial Distortion  
Straight lines appear **curved**, especially near the edges of the image.  
Modeled using coefficients $k_1, k_2, k_3$:  

$$
x_{corr} = x \left(1 + k_1 r^2 + k_2 r^4 + k_3 r^6\right), 
\quad
y_{corr} = y \left(1 + k_1 r^2 + k_2 r^4 + k_3 r^6\right)
$$

---

### 🔹 Tangential Distortion  
Occurs due to **misalignment of lens and sensor**.  
Modeled using $p_1, p_2$:  

$$
x_{corr} = x + \big(2p_1xy + p_2(r^2 + 2x^2)\big), 
\quad
y_{corr} = y + \big(p_1(r^2 + 2y^2) + 2p_2xy\big)
$$

---

✅ Radial distortion bends lines (barrel or pincushion),  
✅ Tangential distortion skews the image due to lens tilt.  
Both must be corrected for accurate calibration and 3D reconstruction.  

---


## Q6. Camera Calibration Procedure (15 marks)

**Q:** Describe the main steps in camera calibration.  

**A:**  
1. Capture images of a known calibration object (e.g., checkerboard).  
2. Identify 3D–2D correspondences (world → image).  
3. Formulate linear equations relating 3D to 2D projection.  
4. Solve for projection matrix $P$ (least squares).  
5. Factorize $P$ into $K, R, t$ to extract intrinsic & extrinsic parameters.  

---

## Q7. Degrees of Freedom in 2D Transformations (10 marks)

**Q:** State the degrees of freedom (DoF) of similarity, affine, and projective transformations.  

**A:**  
- **Translation:** 2 DoF $(t_x, t_y)$  
- **Rigid (rotation + translation):** 3 DoF $(t_x, t_y, \theta)$  
- **Similarity (rotation, translation, uniform scaling):** 4 DoF $(t_x, t_y, \theta, s)$  
- **Affine:** 6 DoF (general linear + translation)  
- **Projective (homography):** 8 DoF (lines not necessarily parallel)  

---

# 🎯 Summary
Exam topics include:  
- Image formation  
- Pinhole model derivation  
- Homogeneous coordinates  
- Intrinsic & extrinsic parameters  
- Distortion  
- Calibration steps  
- DoF of 2D transformations  

Each answer combines **equations + interpretation** (professor-style).  


## Q1. Perspective Projection

**Q:** Derive the pinhole projection equations and implement a Python function to project 3D points $(X,Y,Z)$ onto the 2D image plane using focal length $f$.

---

### 📘 Theory

From similar triangles:

$$
x = \frac{fX}{Z}, 
\quad 
y = \frac{fY}{Z}
$$

This is the **perspective projection equation**.

- $f$: focal length  
- $(X,Y,Z)$: 3D point in world coordinates  
- $(x,y)$: 2D projection on the image plane  

---

In [ ]:
import numpy as np

def project_points(points_3d, f=800):
    # points_3d shape = (N, 3) → [[X,Y,Z],...]
    points_2d = []
    for X, Y, Z in points_3d:
        x = f * X / Z
        y = f * Y / Z
        points_2d.append([x, y])
    return np.array(points_2d)

# 🔑 Cheat: Use f=800, and test with points like (X,Y,Z)=(1.5,2,8)
points = np.array([[1.5, 2.0, 8.0], [0.5, 1.0, 5.0]])
print(project_points(points))


[[150. 200.]
 [ 80. 160.]]


## Q2. Homogeneous Coordinates & Intrinsic Matrix

**Q:** Using homogeneous coordinates, show how 3D points are projected into 2D using the intrinsic matrix $K$. Implement in Python.

---

### 📘 Theory

A 3D point $(X, Y, Z, 1)$ in homogeneous coordinates is projected to 2D image coordinates $(u, v, 1)$ using:

$$
\begin{bmatrix}
u \\ v \\ 1
\end{bmatrix}
\sim
K [R \,|\, t]
\begin{bmatrix}
X \\ Y \\ Z \\ 1
\end{bmatrix}
$$

where  

$$
K =
\begin{bmatrix}
f_x & 0   & c_x \\
0   & f_y & c_y \\
0   & 0   & 1
\end{bmatrix}
$$

- $f_x, f_y$: focal lengths (in pixels)  
- $c_x, c_y$: principal point  
- $R$: $3 \times 3$ rotation matrix (camera orientation)  
- $t$: $3 \times 1$ translation vector (camera position)  

---

In [ ]:
def project_with_intrinsics(points_3d, K):
    # points_3d shape = (N,3)  # K: intrinsic matrix (3x3)
    projected = []
    for X,Y,Z in points_3d:
        vec = np.array([X, Y, Z, 1.0])
        uvw = K @ np.array([[X/Z], [Y/Z], [1]])  # homogeneous
        u, v = uvw[0,0], uvw[1,0]
        projected.append([u, v])
    return np.array(projected)

# 🔑 Cheat: Use fx=800, fy=820, cx=320, cy=240
K = np.array([[800, 0, 320],
              [0, 820, 240],
              [0,   0,   1]])
pts3D = np.array([[1.5, 2.0, 8.0]])
print(project_with_intrinsics(pts3D, K))


[[470. 445.]]


## Q3. Distortion Models

**Q:** Implement radial and tangential distortion correction formulas in code.

---

### 📘 Theory

#### Radial Distortion
Straight lines appear curved due to lens imperfections.  

Corrected coordinates:

$$
x_{corr} = x \left(1 + k_1 r^2 + k_2 r^4 + k_3 r^6 \right)
$$

$$
y_{corr} = y \left(1 + k_1 r^2 + k_2 r^4 + k_3 r^6 \right)
$$

where $r^2 = x^2 + y^2$.

---

#### Tangential Distortion
Caused by lens–sensor misalignment.  

$$
x_{corr} = x + \big(2p_1xy + p_2(r^2 + 2x^2)\big)
$$

$$
y_{corr} = y + \big(p_1(r^2 + 2y^2) + 2p_2xy\big)
$$

---


In [3]:
def distort_points(points, k1=0.1, k2=0.01, p1=0.001, p2=0.001):
    distorted = []
    for x, y in points:
        r2 = x*x + y*y
        # Radial
        x_radial = x * (1 + k1*r2 + k2*r2*r2)
        y_radial = y * (1 + k1*r2 + k2*r2*r2)
        # Tangential
        x_tang = x_radial + (2*p1*x*y + p2*(r2 + 2*x*x))
        y_tang = y_radial + (p1*(r2 + 2*y*y) + 2*p2*x*y)
        distorted.append([x_tang, y_tang])
    return np.array(distorted)

# 🔑 Cheat: Use k1=0.1, k2=0.01, p1=p2=0.001
pts = np.array([[0.5,0.5],[1.0,1.0]])
print(distort_points(pts))


[[0.52775 0.52775]
 [1.246   1.246  ]]


Q4. Calibration with Chessboard (Lab 5.4)

Q: Write OpenCV code to calibrate a camera using multiple chessboard images.

In [12]:
import cv2, glob

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
pattern_size = (9, 6)   # 🔑 7x6 corners

# 3D world points
objp = np.zeros((pattern_size[0]*pattern_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:9, 0:6].T.reshape(-1, 2)
# 🔑 objp.shape = (42,3)

objpoints, imgpoints = [], []
images = glob.glob('assets/A4_Chessboard_9x6.png')  # 🔑 Use your own chessboard images

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # 🔑 gray.shape = (h,w)
    ret, corners = cv2.findChessboardCorners(gray, pattern_size, None)

    if ret:
        objpoints.append(objp)       # (42,3)
        imgpoints.append(corners)    # (42,1,2)

# Calibration
ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
print("Intrinsic K:\n", K)
print("Distortion Coefficients:\n", dist)


Intrinsic K:
 [[3.91505587e+19 0.00000000e+00 1.23950000e+03]
 [0.00000000e+00 3.91505587e+19 1.75350000e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[-6.83667256e-17 -4.36209167e-33 -2.56595134e-08 -4.55400301e-09
  -3.02431165e-49]]


Cheat Notes:

Pattern size = (7,6) corners

objp shape = (42,3)

gray.shape[::-1] = (width, height)

Q5. Image Undistortion (Lab 5.5)

Q: Write code to undistort an image using known calibration parameters.

In [13]:
h, w = img.shape[:2]   # 🔑 e.g. (480,640)

newK, roi = cv2.getOptimalNewCameraMatrix(K, dist, (w,h), 1, (w,h))
dst = cv2.undistort(img, K, dist, None, newK)


Use alpha=1 in getOptimalNewCameraMatrix for full FoV, alpha=0 for cropped FoV.
🔑 Cheat:

alpha=1 → full FoV (black borders remain)

alpha=0 → cropped (no black edges)

Q6. Pose Estimation with solvePnP (Lab 5.6)

Q: Given 3D–2D correspondences, compute camera pose.

In [14]:
retval, rvec, tvec = cv2.solvePnP(objpoints[0], imgpoints[0], K, dist)

# Convert rotation vector → rotation matrix
R, _ = cv2.Rodrigues(rvec)

print("Rotation matrix R:\n", R)   # 🔑 shape (3,3)
print("Translation vector t:\n", tvec)  # 🔑 shape (3,1)


Rotation matrix R:
 [[-0.0921456   0.16473371  0.98202444]
 [-0.37733429  0.90688977 -0.18753607]
 [-0.92148143 -0.38783211 -0.02140623]]
Translation vector t:
 [[-1.31998182e-01]
 [-7.10271035e-01]
 [ 4.24698383e+08]]


In [15]:
axis = np.float32([[0,0,0], [1,0,0], [1,1,0], [0,1,0],   # bottom
                   [0,0,-1],[1,0,-1],[1,1,-1],[0,1,-1]]) # top

imgpts, _ = cv2.projectPoints(axis, rvec, tvec, K, dist)
print("Projected points:", imgpts.shape)  # 🔑 (8,1,2)


Projected points: (8, 1, 2)


# 🎯 Application-Based Follow-Up Questions

---

## Q1. Why do we use multiple chessboard images from different angles during calibration?

**A:**  
- To ensure accurate estimation of both **intrinsic** and **distortion parameters**.  
- Multiple views cover a wide **field of view** and **depth variations**, improving robustness.  
- Prevents overfitting to a single orientation and ensures calibration generalizes across the image plane.  

---

## Q2. What happens if radial distortion is not corrected?

**A:**  
- Straight lines appear **curved** → barrel distortion (outward bulge) or pincushion distortion (inward pinch).  
- Leads to:  
  - Inaccurate **feature matching** in computer vision.  
  - Errors in **3D reconstruction** and structure-from-motion.  
  - Misalignment in **panorama stitching**.  

---

## Q3. How is `solvePnP` related to Augmented Reality (AR)?

**A:**  
- `solvePnP` computes the **camera pose** $(R, t)$ given 3D–2D correspondences.  
- Once pose is known, we can overlay **virtual 3D objects** onto real scenes by projecting them with:

\[
\begin{bmatrix}
u \\ v \\ 1
\end{bmatrix}
\sim
K \; [R \,|\, t]
\begin{bmatrix}
X \\ Y \\ Z \\ 1
\end{bmatrix}
\]


$$
\begin{bmatrix}
u \\
v \\
1
\end{bmatrix}
\;\sim\;
K \; [R \;|\; t] \;
\begin{bmatrix}
X \\
Y \\
Z \\
1
\end{bmatrix}
$$


- This is the mathematical basis of **Augmented Reality (AR)**:  
  - 3D virtual objects appear anchored in the real world.  
  - Ensures consistency of scale, position, and perspective.  
